version: '3'

services:
  metaanchor:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: 'yarn dev:migrate'
    environment:
      POSTGRESQL_PRISMA_URL: postgresql://metaanchor:metaanchor@db/metaanchor_dev?sslmode=disable
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/home/app
      - /home/app/node_modules

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: metaanchor
      POSTGRES_PASSWORD: metaanchor
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
