version: '3'

services:
  digitalsoul:
    build:
      context: .
      target: builder
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    stdin_open: true
    tty: true
    command: 'yarn dev:migrate'
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/srv/app
      - /srv/app/.next
      - /srv/app/node_modules
      - ./ds-data:/srv/data

  db:
    image: postgres:15-alpine
    env_file:
      - .db.env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
