version: '3'

services:
  digitalsoul:
    build:
      context: .
      target: runner
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    command: 'yarn prod:migrate:start'
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    env_file:
      - .db.env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
