version: '3'

services:
  metaanchor:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: 'yarn dev'
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/home/app
      - /home/app/node_modules

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
